function Cmx = fit_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma,alpha_deg,beta_deg, ...
    deltaphi_deg,deltapsi_deg,deltagamma_deg)

%% 1. get the left and right values of Ma,alpha,beta,deltaphi,deltapsi,deltagamma
[Ma_value,Ma_volumn] = get_leftright(Ma_list,Ma);
[alpha_value,alpha_volumn] = get_leftright(alpha_deg_list,alpha_deg);
[beta_value,beta_volumn] = get_leftright(beta_deg_list,beta_deg);
[deltaphi_value,deltaphi_volumn] = get_leftright(deltaphi_deg_list,deltaphi_deg);
[deltapsi_value,deltapsi_volumn] = get_leftright(deltapsi_deg_list,deltapsi_deg);
[deltagamma_value,deltagamma_volumn] = get_leftright(deltagamma_deg_list,deltagamma_deg);

Vol_total = (Ma_volumn(2)-Ma_volumn(1))*(alpha_volumn(2)-alpha_volumn(1))*(beta_volumn(2)-beta_volumn(1));
subVol_total = (deltaphi_volumn(2)-deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_volumn(1));
%% 2. 000
Ma_chosen = Ma_value(1);
alpha_chosen = alpha_value(1);
beta_chosen = beta_value(1);
Vol_000 = (Ma_volumn(2)-Ma)*(alpha_volumn(2)-alpha_deg)*(beta_volumn(2)-beta_deg) / Vol_total;
% 000
subVol_000 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_000 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(1));
% 100
subVol_100 = (deltaphi_deg - deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_100 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(1));
% 010
subVol_010 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_010 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(1));
% 001
subVol_001 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_001 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(2));
% 110
subVol_110 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_110 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(1));
% 101
subVol_101 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_101 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(2));
% 011
subVol_011 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_011 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(2));
% 111
subVol_111 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_111 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(2));
% Cmx_000
Cmx_000 = subCmx_000*subVol_000+subCmx_100*subVol_100+subCmx_010*subVol_010+subCmx_001*subVol_001 ...
    + subCmx_110*subVol_110+subCmx_101*subVol_101+subCmx_011*subVol_011+subCmx_111*subVol_111;
%% 3. 100
Ma_chosen = Ma_value(2);
alpha_chosen = alpha_value(1);
beta_chosen = beta_value(1);
Vol_100 = (Ma-Ma_volumn(1))*(alpha_volumn(2)-alpha_deg)*(beta_volumn(2)-beta_deg) / Vol_total;
% 000
subVol_000 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_000 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(1));
% 100
subVol_100 = (deltaphi_deg - deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_100 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(1));
% 010
subVol_010 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_010 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(1));
% 001
subVol_001 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_001 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(2));
% 110
subVol_110 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_110 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(1));
% 101
subVol_101 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_101 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(2));
% 011
subVol_011 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_011 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(2));
% 111
subVol_111 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_111 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(2));
% Cmx_100
Cmx_100 = subCmx_000*subVol_000+subCmx_100*subVol_100+subCmx_010*subVol_010+subCmx_001*subVol_001 ...
    + subCmx_110*subVol_110+subCmx_101*subVol_101+subCmx_011*subVol_011+subCmx_111*subVol_111;
%% 4. 010
Ma_chosen = Ma_value(1);
alpha_chosen = alpha_value(2);
beta_chosen = beta_value(1);
Vol_010 = (Ma_volumn(2)-Ma)*(alpha_deg-alpha_volumn(1))*(beta_volumn(2)-beta_deg) / Vol_total;
% 000
subVol_000 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_000 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(1));
% 100
subVol_100 = (deltaphi_deg - deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_100 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(1));
% 010
subVol_010 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_010 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(1));
% 001
subVol_001 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_001 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(2));
% 110
subVol_110 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_110 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(1));
% 101
subVol_101 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_101 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(2));
% 011
subVol_011 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_011 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(2));
% 111
subVol_111 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_111 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(2));
% Cmx_010
Cmx_010 = subCmx_000*subVol_000+subCmx_100*subVol_100+subCmx_010*subVol_010+subCmx_001*subVol_001 ...
    + subCmx_110*subVol_110+subCmx_101*subVol_101+subCmx_011*subVol_011+subCmx_111*subVol_111;
%% 5. 001
Ma_chosen = Ma_value(1);
alpha_chosen = alpha_value(1);
beta_chosen = beta_value(2);
Vol_001 = (Ma_volumn(2)-Ma)*(alpha_volumn(2)-alpha_deg)*(beta_deg-beta_volumn(1)) / Vol_total;
% 000
subVol_000 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_000 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(1));
% 100
subVol_100 = (deltaphi_deg - deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_100 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(1));
% 010
subVol_010 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_010 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(1));
% 001
subVol_001 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_001 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(2));
% 110
subVol_110 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_110 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(1));
% 101
subVol_101 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_101 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(2));
% 011
subVol_011 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_011 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(2));
% 111
subVol_111 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_111 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(2));
% Cmx_001
Cmx_001 = subCmx_000*subVol_000+subCmx_100*subVol_100+subCmx_010*subVol_010+subCmx_001*subVol_001 ...
    + subCmx_110*subVol_110+subCmx_101*subVol_101+subCmx_011*subVol_011+subCmx_111*subVol_111;
%% 6. 110
Ma_chosen = Ma_value(2);
alpha_chosen = alpha_value(2);
beta_chosen = beta_value(1);
Vol_110 = (Ma-Ma_volumn(1))*(alpha_deg-alpha_volumn(1))*(beta_volumn(2)-beta_deg) / Vol_total;
% 000
subVol_000 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_000 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(1));
% 100
subVol_100 = (deltaphi_deg - deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_100 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(1));
% 010
subVol_010 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_010 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(1));
% 001
subVol_001 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_001 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(2));
% 110
subVol_110 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_110 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(1));
% 101
subVol_101 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_101 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(2));
% 011
subVol_011 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_011 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(2));
% 111
subVol_111 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_111 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(2));
% Cmx_110
Cmx_110 = subCmx_000*subVol_000+subCmx_100*subVol_100+subCmx_010*subVol_010+subCmx_001*subVol_001 ...
    + subCmx_110*subVol_110+subCmx_101*subVol_101+subCmx_011*subVol_011+subCmx_111*subVol_111;
%% 7. 101
Ma_chosen = Ma_value(2);
alpha_chosen = alpha_value(1);
beta_chosen = beta_value(2);
Vol_101 = (Ma-Ma_volumn(1))*(alpha_volumn(2)-alpha_deg)*(beta_deg-beta_volumn(1)) / Vol_total;
% 000
subVol_000 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_000 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(1));
% 100
subVol_100 = (deltaphi_deg - deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_100 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(1));
% 010
subVol_010 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_010 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(1));
% 001
subVol_001 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_001 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(2));
% 110
subVol_110 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_110 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(1));
% 101
subVol_101 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_101 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(2));
% 011
subVol_011 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_011 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(2));
% 111
subVol_111 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_111 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(2));
% Cmx_101
Cmx_101 = subCmx_000*subVol_000+subCmx_100*subVol_100+subCmx_010*subVol_010+subCmx_001*subVol_001 ...
    + subCmx_110*subVol_110+subCmx_101*subVol_101+subCmx_011*subVol_011+subCmx_111*subVol_111;
%% 8. 011
Ma_chosen = Ma_value(1);
alpha_chosen = alpha_value(2);
beta_chosen = beta_value(2);
Vol_011 = (Ma_volumn(2)-Ma)*(alpha_deg-alpha_volumn(1))*(beta_deg-beta_volumn(1)) / Vol_total;
% 000
subVol_000 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_000 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(1));
% 100
subVol_100 = (deltaphi_deg - deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_100 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(1));
% 010
subVol_010 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_010 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(1));
% 001
subVol_001 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_001 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(2));
% 110
subVol_110 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_110 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(1));
% 101
subVol_101 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_101 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(2));
% 011
subVol_011 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_011 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(2));
% 111
subVol_111 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_111 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(2));
% Cmx_011
Cmx_011 = subCmx_000*subVol_000+subCmx_100*subVol_100+subCmx_010*subVol_010+subCmx_001*subVol_001 ...
    + subCmx_110*subVol_110+subCmx_101*subVol_101+subCmx_011*subVol_011+subCmx_111*subVol_111;
%% 9. 111
Ma_chosen = Ma_value(2);
alpha_chosen = alpha_value(2);
beta_chosen = beta_value(2);
Vol_111 = (Ma-Ma_volumn(1))*(alpha_deg-alpha_volumn(1))*(beta_deg-beta_volumn(1)) / Vol_total;
% 000
subVol_000 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_000 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(1));
% 100
subVol_100 = (deltaphi_deg - deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_100 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(1));
% 010
subVol_010 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_010 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(1));
% 001
subVol_001 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_001 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(1),deltagamma_value(2));
% 110
subVol_110 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_volumn(2)-deltagamma_deg) / subVol_total;
subCmx_110 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(1));
% 101
subVol_101 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_volumn(2)-deltapsi_deg)*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_101 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(1),deltagamma_value(2));
% 011
subVol_011 = (deltaphi_volumn(2)-deltaphi_deg)*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_011 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(1),deltapsi_value(2),deltagamma_value(2));
% 111
subVol_111 = (deltaphi_deg-deltaphi_volumn(1))*(deltapsi_deg-deltapsi_volumn(1))*(deltagamma_deg-deltagamma_volumn(1)) / subVol_total;
subCmx_111 = get_valueCmx(Cmx_row,...
    Ma_list,alpha_deg_list,beta_deg_list, ...
    deltaphi_deg_list,deltapsi_deg_list,deltagamma_deg_list, N, ...
    Ma_chosen,alpha_chosen,beta_chosen,deltaphi_value(2),deltapsi_value(2),deltagamma_value(2));
% Cmx_111
Cmx_111 = subCmx_000*subVol_000+subCmx_100*subVol_100+subCmx_010*subVol_010+subCmx_001*subVol_001 ...
    + subCmx_110*subVol_110+subCmx_101*subVol_101+subCmx_011*subVol_011+subCmx_111*subVol_111;
%% 10. Cmx
Cmx = Cmx_000*Vol_000+Cmx_100*Vol_100+Cmx_010*Vol_010+Cmx_001*Vol_001 ...
    + Cmx_110*Vol_110+Cmx_101*Vol_101+Cmx_011*Vol_011+Cmx_111*Vol_111;